# -*- coding: utf-8 -*-
"""extract_clips.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dllY7Y3bt3pCYCIB9BrL7pR8MAMEUv4I
"""

import cv2
import os

# Function to save short video clips of detected people
def save_video_clip(video_path, bbox, start_frame, end_frame, output_folder="clips"):
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    cap = cv2.VideoCapture(video_path)
    fps = int(cap.get(cv2.CAP_PROP_FPS))
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    out_path = os.path.join(output_folder, f"clip_{start_frame}.mp4")
    out = cv2.VideoWriter(out_path, fourcc, fps, (bbox[2] - bbox[0], bbox[3] - bbox[1]))

    cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

    for _ in range(end_frame - start_frame):
        ret, frame = cap.read()
        if not ret:
            break
        clip = frame[bbox[1]:bbox[3], bbox[0]:bbox[2]]
        out.write(clip)

    cap.release()
    out.release()
    return out_path