# -*- coding: utf-8 -*-
"""yolo_detection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bA0ptIocRJcaiIaSlC-4BTXipAGjt_jX
"""

import cv2
from ultralytics import YOLO

# Load YOLOv5 model
model = YOLO("yolov5s.pt")  # Smallest YOLOv5 model

# Open video file (replace with your video path)
cap = cv2.VideoCapture("retail_video.mp4")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break  # Stop if no more frames

    # Perform detection
    results = model(frame)

    # Draw boxes around detected objects
    for result in results.xyxy[0]:
        x1, y1, x2, y2, conf, cls = map(int, result[:6])
        label = f"{model.names[cls]}: {conf:.2f}"
        cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(frame, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

    # Show the video with detections
    cv2.imshow("Retail Security", frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):  # Press 'q' to quit
        break

cap.release()
cv2.destroyAllWindows()